language: objective-c
os: osx
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode7.1
    - osx_image: beta-xcode6.2
env:
  matrix:
    - FORMULA_VERSION=
    - FORMULA_VERSION=--HEAD
before_install:
  - brew update
  - brew --env
  - brew config
install:
  - mkdir -p $(brew --repo)/Library/Taps/camfort
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/camfort/homebrew-camfort
script:
  - brew install camfort $FORMULA_VERSION --verbose
  - brew audit camfort --strict
  - brew test camfort
  - camfort --version
matrix:
  fast_finish: true
